config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'gdpr', to: 'pages#gdpr'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :folders, only: [:index, :show]
  resources :documents, only: [:show, :new, :create, :edit, :update, :index, :destroy]

end

app/views/shared/_carousel.html.erb
      <!-- body: carousel -->
      <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-inner">
          <!-- first element, active -->
          <div class="carousel-item active">
            <img class="d-block w-100" src="<%= cloudinary_url(@document.photos.first.key) %>" alt="slide 1">
          </div>
          <!-- other elements, inactive at opening -->
          <% if @document.photos.count > 1 %>
            <% @document.photos.each_with_index do |photo, index| %>
              <% if index > 0 %>
                <div class="carousel-item">
                  <img class="d-block w-100" src="<%= cloudinary_url(photo.key) %>" alt="slide <%= index + 1 %> ">
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span><i class="fa fa-angle-left fa-3x arrow-color" aria-hidden="true"></i></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span><i class="fa fa-angle-right fa-3x arrow-color" aria-hidden="true"></i></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <!-- End carousel -->

app/views/shared/_documents.html.erb
<% @documents.each do |document| %>
  <tr class="pointer-cursor" data-link="<%= document_path(document) %>">
    <td class="text-secondary icon-column-width"><i class="far fa-file-alt fa-2x align-document"></i></td>
    <td class="align-text-vertical"><%= document.name %></td>
  </tr>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_folders.html.erb
<table class="table table-borderless table-hover">
  <tbody>
  <!-- Files -->
  <% @folders.each do |folder| %>
    <tr class="pointer-cursor" data-link="<%= folder_path(folder) %>">
      <td class="text-secondary icon-column-width"><i class="fas fa-folder fa-2x"></i></td>
      <td class="align-text-vertical"><%= folder.name %></td>
    </tr>
  <% end %>
  <!-- Documents -->
  <% if ! @documents.empty? %>
    <%= render 'shared/documents', documents: @documents %>
  <% end %>
  </tbody>
</table>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/eth-ivan" target="_blank"><i class="fab fa-github"></i><p class="github-name">Ivan P.</p></a>
    <a href="https://github.com/antoinero" target="_blank"><i class="fab fa-github"></i><p class="github-name">Antoine R.</p></a>
    <a href="https://github.com/ismooz" target="_blank"><i class="fab fa-github"></i><p class="github-name">Ismaël G.</p></a>
  </div>
  <div class="footer-copyright">
    Batch 507 - 2020-2021 | Made by an extraordinary team with <i class="fas fa-heart"></i> and 🍺 at Le Wagon
  </div>
</div>

app/views/shared/_gdpr.html.erb
<!-- Modal -->
<div class="modal fade" id="gdprModal" tabindex="-1" aria-labelledby="gdprModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Privacy Policy for Safedoc</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <p>At Safedoc, accessible from https://safedoc.herokuapp.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Safedoc and how we use it.</p>

      <h4>General Data Protection Regulation (GDPR)</h4>
      <p>We are a Data Controller of your information.</p>

      <p>Safedoc legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:</p>
      <ul>
          <li>Safedoc needs to perform a contract with you</li>
          <li>You have given Safedoc permission to do so</li>
          <li>Processing your personal information is in Safedoc legitimate interests</li>
          <li>Safedoc needs to comply with the law</li>
      </ul>

      <p>Safedoc will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.</p>

      <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. If you wish to be informed what Personal Information we hold about you and if you want it to be removed from our systems, please contact us.</p>
      <p>In certain circumstances, you have the following data protection rights:</p>
      <ul>
          <li>The right to access, update or to delete the information we have on you.</li>
          <li>The right of rectification.</li>
          <li>The right to object.</li>
          <li>The right of restriction.</li>
          <li>The right to data portability</li>
          <li>The right to withdraw consent</li>
      </ul>

      <h4>Log Files</h4>

      <p>safedoc.herokuapp.com follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

      <h4>Privacy Policies</h4>

      <P>You may consult this list to find the Privacy Policy for each of the advertising partners of safedoc.herokuapp.com.</p>

      <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on safedoc.herokuapp.com, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

      <p>Note that safedoc.herokuapp.com has no access to or control over these cookies that are used by third-party advertisers.</p>

      <h4>Third Party Privacy Policies</h4>

      <p>safedoc.herokuapp.com's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>

      <p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

      <h4>Children's Information</h4>

      <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

      <p>safedoc.herokuapp.com does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

      <h4>Online Privacy Policy Only</h4>

      <p>Our Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in safedoc.herokuapp.com. This policy is not applicable to any information collected offline or via channels other than this website.</p>

      <h4>Consent</h4>

      <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-dark navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_safedoc.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ajouter doc", new_document_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dossiers", folders_path, class: "nav-link text-info" %>
        </li>
         <!--  <li class="nav-item">
          <%= link_to "Rappels", folders_path, class: "nav-link text-info" %>
        </li> -->
        <li class="nav-item">
          <%= link_to '<i class="fas fa-search"></i> Search'.html_safe, documents_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.profile_image.attached? %>
            <%= cl_image_tag current_user.profile_image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else  %>
            <%= image_tag "default-avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Prix", pricing_path, class: "dropdown-item text-info" %>
            <%= link_to "FAQ", faq_path, class: "dropdown-item text-info" %>
            <%= link_to "Editer profile", edit_user_registration_path, class: "dropdown-item text-info" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-info" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "Prix", pricing_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "A notre propos", about_path, class: "nav-link text-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "FAQ", faq_path, class: "nav-link text-info mr-5" %>
        </li>
        <li>
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-info mr-2" %>
        </li>
        <li>
          <%= link_to "S'enregistrer", new_user_registration_path, class: "btn btn-outline-info" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_mobile.html.erb
<div class="navbar-mobile">
  <div>
    <%= link_to '<i class="fas fa-home fa-2x"></i>'.html_safe, root_path, class: "nav-link text-info" %>
  </div>
  <div>
    <%= link_to '<i class="fas fa-search fa-2x"></i>'.html_safe, documents_path, class: "nav-link text-info" %>
  </div>
  <div>
    <%= link_to '<i class="fas fa-plus fa-2x"></i>'.html_safe, new_document_path, class: "nav-link text-info" %>
  </div>
  <div>
    <%= link_to '<i class="fas fa-folder fa-2x"></i>'.html_safe, folders_path, class: "nav-link text-info" %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav id="sidebar">
  <div class="custom-menu">
    <button type="button" id="sidebarCollapse" class="btn btn-primary">
      <i class="fa fa-plus text-info"></i>
    </button>
  </div>
  <div class="p-4">
    <h1><a href="index.html" class="logo">Safedoc <span>best app ever</span></a></h1>
    <ul class="list-unstyled components mb-5">
      <li>
        <%= link_to '<i class="fa fa-plus mr-3"></i> Add file'.html_safe, new_document_path, class: "nav-link text-info" %>
      </li>
      <li>
        <%= link_to '<i class="fas fa-folder mr-3"></i> Folders'.html_safe, folders_path, class: "nav-link text-info" %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-user mr-3"></i> My profile'.html_safe, edit_user_registration_path, class: "nav-link text-info" %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-cog mr-3"></i> Configure'.html_safe, edit_user_registration_path, class: "nav-link text-info" %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-paper-plane mr-3"></i> Contact'.html_safe, edit_user_registration_path, class: "nav-link text-info" %>
      </li>
    </ul>

  </div>
</nav>