config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'gdpr', to: 'pages#gdpr'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :folders, only: [:index, :show]
  resources :documents, only: [:show, :new, :create, :edit, :update, :index, :destroy]

end

app/views/pages/about.html.erb
<div class="container bg-white">

  <h1 class="title1">About us</h1>

  <hr class="hr-title-about mb-5">

  <em><h2 class="text-center op">The dev team</h2></em>
  <hr class="mt-5 mb-5">

  <div class="d-flex mt-5">
    <%= image_tag "ivan.png", style: "height:250px;width:auto;", class: "avatar-about lr"%>

    <div class="ml-5 my-auto avatar-text ud">
      <h2>Ivan Perroud</h2>
      <p>Passionate about cryptocurrencies, I work for a small company in Lausanne. Student in le Wagon to discover web technologies, and looking to work for a crypto company as technical project manager or data analyst. Ideally, I would work and code at the top of a mountain.</p>
      <div class="text-right">
        <span class="mr-3 text-muted">Follow him on</span>
        <a href="https://github.com/eth-ivan" target="_blank"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>

  </div>

  <hr class="hr-dotted">

  <div class="d-flex mt-5">

    <div class="mr-5 my-auto avatar-text ud text-right">
      <h2>Antoine Robert</h2>
      <p>Viewing myself as somebody curious with eclectic interests and a taste for challenges, I am an eager learner craving new experiences. Inspired by my travels, on sea as on land, I seek to evolve in a multicultural world and enrich myself from the people on my road. Logical and adventurous, I find a state of satisfaction and serenity in coding.
      </p>
      <div class="text-left">
        <span class="mr-3 text-muted">Follow him on</span>
        <a href="https://github.com/antoinero" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/anonio9/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/antoine.robert.31542" target="_blank"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/antoine-robert-660439b/"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <%= image_tag "antoine.png", style: "height:250px;width:auto;", class: "avatar-about rl"%>
  </div>

  <hr class="hr-dotted">

  <div class="d-flex mt-5">
    <%= image_tag "ismael.png", style: "height:250px;width:auto;", class: "avatar-about lr"%>

    <div class="ml-5 my-auto avatar-text ud">
      <h2>Ismaël Gashi</h2>
      <p>A health insurance specialist with nearly 15 years of experience in the field, I decided to redirect my career as a web developer 💻 with Le Wagon in batch #507. I have created several sites in the insurance field. I love technology and for me, internet is the future.</p>
      <div class="text-right">
        <span class="mr-3 text-muted">Follow him on</span>
        <a href="https://github.com/ismooz" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/ismoo/" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/ismael.gashi" target="_blank"><i class="fab fa-facebook"></i></a>
        <a href="https://twitter.com/ismoo83" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/ismaelgashi/" target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>

  </div>

  <hr class="hr-dotted">

</div>

app/views/pages/faq.html.erb
<div class="container bg-white">
  <h2>FAQ</h2>
  <br>
  <div class="row">
    <ul>
      <li>
        <strong>
          Can I save any documents ?
        </strong>

        <p>
          For the moment any jpeg documents can be saved
        </p>

      </li>

      <li>
        <strong>
          Can I change the deadline of one of my document
        </strong>

        <p>
          Yes, go to update my document
        </p>

      </li>

       <li>
        <strong>
          Who can see my documents ?
        </strong>

        <p>
          We are taking privacy seriously and obviously only you can see your documents !
        </p>
      </li>

      </li>

       <li>
        <strong>
          I would like to see how my informations are treated
        </strong>

        <p>
          See the <%= link_to 'general data protection regulation', gdpr_path %>
        </p>
      </li>
    </ul>
  </div>
</div>

app/views/pages/gdpr.html.erb
<div class="container bg-white">
  <h2>General Data Protection Regulation</h2>
  <br>
  <div class="row">
    <ul>
      <li>
        <strong>
          Documents Database:
        </strong>

        <p>
          We save your documents on Cloudinary
        </p>

      </li>

      <li>
        <strong>
          Document use:
        </strong>

        <p>
          We do not use nor sell your documents for marketing purpose nor advetisement
        </p>

      </li>

       <li>
        <strong>
          Document access:
        </strong>

        <p>
          Only you can see your documents
        </p>

      </li>

    </ul>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container bg-white">

  <% if user_signed_in? %>

  <div>

    <h2><i class="far fa-clock"></i> Mes prochaines deadlines</h2>
    <br>

    <div class="row">
      <% if @documents_sorted_deadline.length > 0%>

        <% @documents_sorted_deadline.each do |document| %>
            <div class="col-xs-12 col-md-6 col-lg-4">
              <div class="card-product">
                <%= link_to document do %>
                  <div>
                    <%= cl_image_tag(document.photos.first.key) %>
                  </div>
                  <div class="card-product-infos">
                    <div>
                      <h2><%= document.name %></h2>
                      <% if document.expire.presence && document.expire > 0 && document.expire < 30 %>
                        <p style="color: red; font-weight: bold;"><%= "#{document.expire_string}" %></p>
                      <% else document.expire.presence && document.expire > 0 %>
                        <p><%= "#{document.expire_string}" %></p>
                      <% end %>
                    </div>
                    <div class="btn-group">
                      <%= link_to 'View', document_path(document), class: "btn btn-sm btn-outline-secondary rounded-left" %>
                      <%= link_to 'Edit', edit_document_path(document), class: "btn btn-sm btn-outline-secondary rounded-right" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
        <% end %>
      <% else %>
        <div class="col-xs-12 col-md-6 col-lg-4">
          <div>
            <em>Bon travail ! Pas d'échéance en cours...</em>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <hr>

  <div class="pt-5 mb-5">

      <h2><i class="far fa-clock"></i> Mes derniers documents sauvegardés</h2>
      <br>

    <div class="row">
      <% if @documents_sorted_creation.length > 0 %>
        <% @documents_sorted_creation.each do |document| %>

          <div class="col-xs-12 col-md-6 col-lg-4">

            <div class="card-product">
              <%= link_to document do %>

                <div>
                  <%= cl_image_tag(document.photos.first.key) %>

                  <div class="card-product-infos">

                    <div>
                      <h2><%= document.name %></h2>
                      <p><%= "Created at #{ document.created_at.strftime("%d.%m.%Y") }" %></p>
                    </div>
                      <div class="btn-group">
                        <%= link_to 'View', document_path(document), class: "btn btn-sm btn-outline-secondary rounded-left" %>
                        <%= link_to 'Edit', edit_document_path(document), class: "btn btn-sm btn-outline-secondary rounded-right" %>
                      </div>
                  </div>

                </div>

              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>

        <div class="col-xs-12 col-md-6 col-lg-4">

          <div>
            <em>Pas de documents ajoutés pour l'instant...</em>
            <%= link_to '<i class="fas fa-plus"></i> Add a new doc'.html_safe, new_document_path, class: "btn btn-primary"  %>
          </div>

        </div>
      <% end %>
    </div>

  </div>

  <% else %>

  <div class="mb-5">

    <div class="title1 mb-5 text-center">
      <h1>Classez vos documents 📄 intelligemment, <br> Utilisez Safedoc !</h1>
      <div>
        <em>"Safedoc est une application créée pour vous aider à sauvegarder tous vos documents importants au même endroit et gère l'échéance de vos contrats."</em>
      </div>

    </div>

        <hr>

      <div class="d-flex mt-5 mb-5">
        <%= image_tag "iphone.png", style: "height:400px;width:auto;", class: "img1-homepage"%>

        <div class="ml-5 my-auto text1-hompage">
          <h2>🖨 Scanez avec votre smartphone</h2>
          <p>Ne perdez plus constamment vos garanties, contrats et autres documents. Retrouvez-les tous dans une seule application. Sécurisée, pratique et indispensable. L'application "made in 🇨🇭 Switzerland 🇨🇭".</p>
          <%= link_to "S'enregistrer !", new_user_registration_path, class: "btn btn-outline-info" %>
        </div>

      </div>

      <hr>

      <div class="d-flex mt-5">

        <div class="mr-5 my-auto text1-hompage text-right">
          <h2>🔎 Trouvez vos documents !</h2>
          <p>Vous pouvez facilement retrouver vos documents où que vous soyez. Modifiez-les ou ajoutez simplement un rappel pour ne pas oublier la date d'échéance...</p>
          <%= link_to "S'enregistrer !", new_user_registration_path, class: "btn btn-outline-info" %>
        </div>
        <%= image_tag "doc_preview.png", style: "height:300px;width:auto;", class: "img2-homepage"%>

      </div>

    </div>
  <% end %>
</div>

app/views/pages/pricing.html.erb
<div class="container bg-white">
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">You can choose your plan according to your needs. Your data are safe and available at all times.</p>
</div>
<div class="card-deck mb-3 text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Free</h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">CHF 0 <small class="text-muted">/ mo</small></h1>
      <ul class="list-unstyled text-left ml-5 mt-3 mb-4">
        <li><i class="fas fa-check"></i> users included</li>
        <li><i class="fas fa-check"></i> 1 GB of storage</li>
        <li class="text-muted"><i class="fas fa-times"></i> OCR document</li>
        <li><i class="fas fa-check"></i> Email support</li>
        <li class="text-muted"><i class="fas fa-times"></i> Help center access</li>
      </ul>
      <%= link_to "Sign up for free", new_user_registration_path, class: "btn btn-lg btn-block btn-outline-info" %>
    </div>
  </div>
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Pro</h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">CHF 9 <small ass="text-muted"cl>/ mo</small></h1>
      <ul class="list-unstyled text-left ml-5 mt-3 mb-4">
        <li><i class="fas fa-check"></i> 5 users included</li>
        <li><i class="fas fa-check"></i> 10 GB of storage</li>
        <li><i class="fas fa-check"></i> OCR document</li>
        <li><i class="fas fa-check"></i> Priority email support</li>
        <li><i class="fas fa-check"></i> Help center access</li>
      </ul>
      <%= link_to "Get started", new_user_registration_path, class: "btn btn-lg btn-block btn-info" %>
    </div>
  </div>
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Enterprise</h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">CHF 29 <small class="text-muted">/ mo</small></h1>
      <ul class="list-unstyled text-left ml-5 mt-3 mb-4">
        <li><i class="fas fa-check"></i> +10 users included</li>
        <li><i class="fas fa-check"></i> 50 GB of storage</li>
        <li><i class="fas fa-check"></i> OCR document</li>
        <li><i class="fas fa-check"></i> Phone and email support</li>
        <li><i class="fas fa-check"></i> Help center access</li>
      </ul>
      <%= link_to "Contact us", new_user_registration_path, class: "btn btn-lg btn-block btn-info" %>
    </div>
  </div>
</div>

 <div>
    <br>
    <hr class="mb-5">
    <h2 class="text-center mb-5">More question ?</h2>
      <div class="text-center">
        <%= link_to "To FAQ", faq_path, class: "text-center btn btn-lg btn-info" %>
      </div>
  </div>